### ISSUE TITLE
Question about the hook behaviour

### ISSUE THREAD

**Issue by AtunDesenfrenado** [KyperTrast/lithium-minus#1]
First of all thank you for doing this, I've been having so much fun with this mod.
Lithium is my favorite mod along with RA2 and Action.

I was wondering if I'm doing something wrong because the hook is supposed to release and stay as long as you press the key, and it will let go when you release the key or when the hook_time reach its limit.

Now with the toggle mode I must click first and then click again to let go. It's difficult to perform certain pull movements like I used to did.

And if I remember correctly the hook command was an alias or something so you had to bind it with a + before to make the hook release when you stopped clicking.

Or maybe I'm doing something wrong.
Either way I'm having a blast with the mod.

Thank you!

**Comment by KyperTrast** [comment]
The new hook_toggle command does not replace the original behaviour, this was just added as an alternate method.

The +hook / alias method still works but you have to create the alias yourself; the original mod "stuffed" the alias commands for you but the rerelease appears to have tightened security on command stuffing so just binding a key to +hook won't work.

You can create the +hook/-hook alias with the following one-liner:
alias +hook hook ; alias -hook unhook

Then whatever key you have bound to +hook will now work. This method is tucked away in the lith_help command / lm_help.cpp but I have updated the README instructions with this as well.
