### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [KyperTrast/lithium-minus#2]
Hi!,
I'm not sure how to proceed with this repository. There are no VS project or solution files and no make or cmake files. Opening the folder and files in VS2022 shows undefined items and constants. How does one use this project? Are we supposed drop this into the re-release dll directory?

**Comment by KyperTrast** [comment]
yes, you will first need to grab the source code from the id software repo, replace any existing files (ex. g_local.h) with the Lithium-modified ones, and then add the remaining Lithium-specific files (ex. l_rune.cpp, l_hook.cpp) to the project that is included there

I was trying to be "smart" and only pushed files I modified/created but after looking at existing projects it makes more sense to just include everything, my next commit will include all source code files and project files to build them

**Comment by QwazyWabbitWOS** [comment]
Thank you. That would be fine. Yes, the repo should contain all the files needed since it encompasses all changes and references. The way it is right now, declarations and definitions are missing for Edict_ForceLookAtPoint and Bot_PickedUpItem.

**Comment by QwazyWabbitWOS** [comment]
Got a good build after tinkering with it on your recommendations for the l_*.cpp files not included in the project. Those and the lm_help.cpp file. A new morning and a new cup of coffee does wonders for the brain.
